server:
  port: 8085
  servlet:
    context-path: /tv2
playwright.headless: true

spring:
  cache.type: redis
  data:
    redis:
      host: 192.168.1.222
      port: 6379
  pid:
    file: tv2p.pid
springdoc:
  swagger-ui:
    path: /

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      access: unrestricted
tmdb:
  api-key:
